phases:
  install:
    commands:
    - echo Entered the install phase...
    - apt-get update -y
    - apt-get install -y npm
    - npm -v
    finally:
    - echo This always runs even if the update or install command fails