version: 0.1

phases:
  install:
    commands:
    - echo Entered the install phase...
    finnaly:
    - echo finnaly Entered the install phase...
  pre-build:
    commands:
    - echo pre-build
    finnaly:
    - echo finnaly Entered the install phase...
  build:
    commands:
    - echo build
    finnaly:
    - echo finnaly Entered the install phase...
  post-build:
    commands:
    - echo post-build
    finnaly:
    - echo finnaly Entered the install phase...